name: brent-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pymc3>=3.11
  - arviz>=0.12
  - pandas>=1.4
  - numpy>=1.21
  - scipy>=1.8
  - matplotlib>=3.5
  - seaborn>=0.11
  - plotly>=5.0
  - jupyter>=1.0
  - jupyterlab>=3.3
  - flask>=2.2
  - requests>=2.28
  - scikit-learn>=1.1
  - statsmodels>=0.13
  - yfinance>=0.1.70
  - fredapi>=0.4
  - python-dotenv>=0.19
  - pytest>=7.0
  - black>=22.0
  - flake8>=4.0
  - pip
  - pip:
    - streamlit>=1.20
    - dash>=2.4
    - dash-bootstrap-components>=1.2 